# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-ctop" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "ffec9980ecf80cfc2771f4f4620e0dbbe47f7fe3d2c4b415b6d8d5f6945566f3"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_darwin_arm64"
      binary "kubectl-ctop_darwin_arm64", target: "kubectl-ctop"
    end
    on_intel do
      sha256 "625a4170b833dd2483dd011861b56ad496891a29ed87b28f8134259f430be52a"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_darwin_amd64"
      binary "kubectl-ctop_darwin_amd64", target: "kubectl-ctop"
    end
  end
  on_linux do
    on_arm do
      sha256 "3ec64e7ac9e455779a465bf961ff623a138eb4d7af0019479ba82af757a88a3e"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_linux_arm64"
      binary "kubectl-ctop_linux_arm64", target: "kubectl-ctop"
    end
    on_intel do
      sha256 "636dc5219547ffca2f558f3bdfbc468aaa51e410a9de93442aeee3691d1196cb"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_linux_amd64"
      binary "kubectl-ctop_linux_amd64", target: "kubectl-ctop"
    end
  end

  name "kubectl-ctop"
  desc "CTop is a kubectl plugin for top-like monitoring of Kubernetes historical resource usage"
  homepage "https://github.com/sergelogvinov/kubernetes-custom-metrics"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-ctop_darwin_#{arch}"]
    end
  end

  # No zap stanza required
end
