# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-ctop" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f0f934196eb9f27ce120f130dba4096c89d80057257c4a65c72a9785da8e32dd"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_darwin_arm64"
      binary "kubectl-ctop_darwin_arm64", target: "kubectl-ctop"
    end
    on_intel do
      sha256 "203706a720c9c8132529ede94dd5081e5d516ac3f035041b9ff10ff6364184c2"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_darwin_amd64"
      binary "kubectl-ctop_darwin_amd64", target: "kubectl-ctop"
    end
  end
  on_linux do
    on_arm do
      sha256 "fbdc079241cec486d35d6300b410914854e9622f7522c5584a51103523038dad"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_linux_arm64"
      binary "kubectl-ctop_linux_arm64", target: "kubectl-ctop"
    end
    on_intel do
      sha256 "80f62990a53e5c4927d57fdcfb35de6bcebf133b0919c2e2744e37757a34272a"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_linux_amd64"
      binary "kubectl-ctop_linux_amd64", target: "kubectl-ctop"
    end
  end

  name "kubectl-ctop"
  desc "CTop is a kubectl plugin for top-like monitoring of Kubernetes historical resource usage"
  homepage "https://github.com/sergelogvinov/kubernetes-custom-metrics"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-ctop_darwin_#{arch}"]
    end
  end

  # No zap stanza required
end
