# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-ctop" do
  arch arm: "arm64", intel: "amd64"

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "8422bd9740fbb7aeaaebef0b8e6f00dd71f8408bd44b5ca7268ff9af6e64afea"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_darwin_arm64"
      binary "kubectl-ctop_darwin_arm64", target: "kubectl-ctop"
    end
    on_intel do
      sha256 "04f76a15b011783553b1ccf168da84a02d026f4c5317edc95acde479d25e7e3e"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_darwin_amd64"
      binary "kubectl-ctop_darwin_amd64", target: "kubectl-ctop"
    end
  end
  on_linux do
    on_arm do
      sha256 "a09a79be3321dde872529fa4a6b0a7fed79791ef2fbef317fccffd65f79174c3"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_linux_arm64"
      binary "kubectl-ctop_linux_arm64", target: "kubectl-ctop"
    end
    on_intel do
      sha256 "41950514ee9892dcc32c8f7a1e5563bef2ea25d4db13864b6f04552fc8e4f196"
      url "https://github.com/sergelogvinov/kubernetes-custom-metrics/releases/download/v#{version}/kubectl-ctop_linux_amd64"
      binary "kubectl-ctop_linux_amd64", target: "kubectl-ctop"
    end
  end

  name "kubectl-ctop"
  desc "CTop is a kubectl plugin for top-like monitoring of Kubernetes historical resource usage"
  homepage "https://github.com/sergelogvinov/kubernetes-custom-metrics"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-ctop_darwin_#{arch}"]
    end
  end

  # No zap stanza required
end
