# This file was generated by GoReleaser. DO NOT EDIT.
cask "mimiops-mcp" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"
  binary "mimiops-mcp_#{os}_#{arch}", target: "mimiops-mcp"

  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "f38ac7323efda2f4353d4cf9ab7b86e3ad0679061fcfadae1555a3118c228875"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_darwin_amd64"
      binary "mimiops-mcp_darwin_amd64", target: "bin/mimiops-mcp"
    end
    on_arm do
      sha256 "9e2ab42a060acb9cd7023bba126cedf8f75126b48893b86ae30f3fc45ba16ed0"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_darwin_arm64"
      binary "mimiops-mcp_darwin_arm64", target: "bin/mimiops-mcp"
    end
  end

  on_linux do
    on_intel do
      sha256 "fdc98249af26932346a77be2217abd22a7705b14fd906718648b986664632454"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_linux_amd64"
      binary "mimiops-mcp_linux_amd64", target: "bin/mimiops-mcp"
    end
    on_arm do
      sha256 "17d0c362d3aad15d56b65e4bb72f715e836095ce82ba8480c3234e9e7c1722ff"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_linux_arm64"
      binary "mimiops-mcp_linux_arm64", target: "bin/mimiops-mcp"
    end
  end

  name "mimiops-mcp"
  desc "MimiOps is an opinionated MCP server for Kubernetes"
  homepage "https://github.com/sergelogvinov/mimiops-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mimiops-mcp_darwin_#{arch}"]
    end
  end

  # No zap stanza required

end
