# This file was generated by GoReleaser. DO NOT EDIT.
cask "mimiops-mcp" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"
  binary "mimiops-mcp_#{os}_#{arch}", target: "mimiops-mcp"

  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "59cf84a4033aee0a0759db4943310668240d9ba1c10a8211f14a3f890289f293"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_darwin_amd64"
      binary "mimiops-mcp_darwin_amd64", target: "bin/mimiops-mcp"
    end
    on_arm do
      sha256 "6c3686d13a61ea126e01ce01fbb696d0bfb61816febf0db9c993622ce57cdbc3"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_darwin_arm64"
      binary "mimiops-mcp_darwin_arm64", target: "bin/mimiops-mcp"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4f063b7c8fb7add02e2981c43fcdd0585c2107462f0f79f0420b549ab8bf4e8"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_linux_amd64"
      binary "mimiops-mcp_linux_amd64", target: "bin/mimiops-mcp"
    end
    on_arm do
      sha256 "db74e362fec391eda1d88cf0bdba6b9a2fc8f115efd712701d6ec338aef6cc3b"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_linux_arm64"
      binary "mimiops-mcp_linux_arm64", target: "bin/mimiops-mcp"
    end
  end

  name "mimiops-mcp"
  desc "MimiOps is an opinionated MCP server for Kubernetes"
  homepage "https://github.com/sergelogvinov/mimiops-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mimiops-mcp_darwin_#{arch}"]
    end
  end

  # No zap stanza required

end
