# This file was generated by GoReleaser. DO NOT EDIT.
cask "mimiops-mcp" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"
  binary "mimiops-mcp_#{os}_#{arch}", target: "mimiops-mcp"

  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "4c6bf020d36e91e7dad3a437ecddbfbfc61228d04a79be9ec42c037b164cd58a"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_darwin_amd64"
      binary "mimiops-mcp_darwin_amd64", target: "bin/mimiops-mcp"
    end
    on_arm do
      sha256 "8f11510db40b9c0a4ae7150088a3b94dafc3714a09597a333db4b9c31e8abd62"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_darwin_arm64"
      binary "mimiops-mcp_darwin_arm64", target: "bin/mimiops-mcp"
    end
  end

  on_linux do
    on_intel do
      sha256 "9c7a6c2dd176de639fd1cffa7dc7e3e02b601d2c67f6ee14d9d10ab7edd27c22"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_linux_amd64"
      binary "mimiops-mcp_linux_amd64", target: "bin/mimiops-mcp"
    end
    on_arm do
      sha256 "dac5ba128864148435a1f081144de90f541b3167b3176edff5765c7931a01dde"
      url "https://github.com/sergelogvinov/mimiops-mcp/releases/download/v#{version}/mimiops-mcp_linux_arm64"
      binary "mimiops-mcp_linux_arm64", target: "bin/mimiops-mcp"
    end
  end

  name "mimiops-mcp"
  desc "MimiOps is an opinionated MCP server for Kubernetes"
  homepage "https://github.com/sergelogvinov/mimiops-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mimiops-mcp_darwin_#{arch}"]
    end
  end

  # No zap stanza required

end
