# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxmox-mcp" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"
  binary "proxmox-mcp_#{os}_#{arch}", target: "proxmox-mcp"

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "77e04c1c938a16b00e5655dd26216b08e181eb3cab61c7b3e14a9d19fba439eb"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_darwin_arm64"
      binary "proxmox-mcp_darwin_arm64", target: "proxmox-mcp"
    end
    on_intel do
      sha256 "34059c464cf57e631fbbd727ef6d7eafa50f67289e5059dde3ded65b04bae0cd"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_darwin_amd64"
      binary "proxmox-mcp_darwin_amd64", target: "proxmox-mcp"
    end
  end
  on_linux do
    on_arm do
      sha256 "55f193297cc6822401ad1d31acc398bbe61d94e580941f3fc655c14e5fbd6319"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_linux_arm64"
      binary "proxmox-mcp_linux_arm64", target: "proxmox-mcp"
    end
    on_intel do
      sha256 "3a0c105834829fcbcaa8a88fc566d82c7e8ff9acb5c7916184ba5334dd22138e"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_linux_amd64"
      binary "proxmox-mcp_linux_amd64", target: "proxmox-mcp"
    end
  end

  name "proxmox-mcp"
  desc "Proxmox MCP is an opinionated MCP server"
  homepage "https://github.com/sergelogvinov/proxmox-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proxmox-mcp_darwin_#{arch}"]
    end
  end

  # No zap stanza required
end
