# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxmox-mcp" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"
  binary "proxmox-mcp_#{os}_#{arch}", target: "proxmox-mcp"

  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "d4cb67aa703709a1c9dc8dcfc80cef022178e8020c94301ac8819076e3311621"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_darwin_arm64"
      binary "proxmox-mcp_darwin_arm64", target: "proxmox-mcp"
    end
    on_intel do
      sha256 "7477e61f171d3fd1f1a958d6e58380893755375729084eec26caae706ef8ea63"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_darwin_amd64"
      binary "proxmox-mcp_darwin_amd64", target: "proxmox-mcp"
    end
  end
  on_linux do
    on_arm do
      sha256 "09488a8d6d8d8232c3cff445d8f2286e1cf6fcdbca90abe2a26e62f571afd29d"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_linux_arm64"
      binary "proxmox-mcp_linux_arm64", target: "proxmox-mcp"
    end
    on_intel do
      sha256 "14bf7fc686037cc28ce4e59237d46a7a016e3187836d0908374f8214167d7452"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_linux_amd64"
      binary "proxmox-mcp_linux_amd64", target: "proxmox-mcp"
    end
  end

  name "proxmox-mcp"
  desc "Proxmox MCP is an opinionated MCP server"
  homepage "https://github.com/sergelogvinov/proxmox-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proxmox-mcp_darwin_#{arch}"]
    end
  end

  # No zap stanza required
end
