# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxmox-mcp" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"
  binary "proxmox-mcp_#{os}_#{arch}", target: "proxmox-mcp"

  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "b1fb523abaf372ff71c9f0e451375e9ca689d67c92877a8c0d520f2ff28a8c1f"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_darwin_arm64"
      binary "proxmox-mcp_darwin_arm64", target: "proxmox-mcp"
    end
    on_intel do
      sha256 "7bb0ad348b12fbc25b8531fb110a1ac43755fd49b1e12f63a54bc0b812b9dad2"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_darwin_amd64"
      binary "proxmox-mcp_darwin_amd64", target: "proxmox-mcp"
    end
  end
  on_linux do
    on_arm do
      sha256 "278675e8cb7ed38c810eee422f080d7776e21009f2fe30e6a95b2a0be0a2c3d1"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_linux_arm64"
      binary "proxmox-mcp_linux_arm64", target: "proxmox-mcp"
    end
    on_intel do
      sha256 "aae5bb1cbe766ae8cecf569cd32420dc79185364e65d7e20cdcb12f3ac8dd78f"
      url "https://github.com/sergelogvinov/proxmox-mcp/releases/download/v#{version}/proxmox-mcp_linux_amd64"
      binary "proxmox-mcp_linux_amd64", target: "proxmox-mcp"
    end
  end

  name "proxmox-mcp"
  desc "Proxmox MCP is an opinionated MCP server"
  homepage "https://github.com/sergelogvinov/proxmox-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proxmox-mcp_darwin_#{arch}"]
    end
  end

  # No zap stanza required
end
