# This file was generated by GoReleaser. DO NOT EDIT.
cask "pvecsictl" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"
  binary "pvecsictl-#{os}-#{arch}", target: "pvecsictl"

  version "0.20.0"

  on_macos do
    on_intel do
      sha256 "5dc0b26c269539e4688dbe0d9164e038b5a4853f7dda9be1a31af18aff862ede"
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-darwin-amd64"
      binary "pvecsictl-darwin-amd64", target: "pvecsictl-darwin-amd64"
    end
    on_arm do
      sha256 "d665e56684af8b2e85e332c73352702f4017aa32b4bffc74ceae60b5e78ca95f"
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-darwin-arm64"
      binary "pvecsictl-darwin-arm64", target: "pvecsictl-darwin-arm64"
    end
  end

  on_linux do
    on_intel do
      sha256 "d0605c37b44bd734ab188adeb68b52157c25d070eaaea244f02ffc5f57eedc75"
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-linux-amd64"
      binary "pvecsictl-linux-amd64", target: "pvecsictl-linux-amd64"
    end
    on_arm do
      sha256 "0e0432d8e8c0ec409e32a838034cf713c0b4cfd5c9ec325612dee9340816e6ca"
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-linux-arm64"
      binary "pvecsictl-linux-arm64", target: "pvecsictl-linux-arm64"
    end
  end

  name "pvecsictl"
  desc "Proxmox VE CSI Mutate tool"
  homepage "https://github.com/sergelogvinov/proxmox-csi-plugin"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pvecsictl-darwin-#{arch}"]
    end
  end

  # No zap stanza required

end
