# This file was generated by GoReleaser. DO NOT EDIT.
cask "pvecsictl" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"
  binary "pvecsictl-#{os}-#{arch}", target: "pvecsictl"

  name "pvecsictl"
  desc "Proxmox VE CSI Mutate tool"
  homepage "https://github.com/sergelogvinov/proxmox-csi-plugin"
  version "0.18.0"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-darwin-amd64"
      sha256 "1bc46af5ae36bd7268000b7ece3795fd5110b8fa6226fafb49a32ca20e054935"
      binary "pvecsictl-darwin-amd64", target: "pvecsictl-darwin-amd64"
    end
    on_arm do
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-darwin-arm64"
      sha256 "5d482f485ae625cc4675f3dadf3cccd119288b4fb9e7740f48aa62c3e2145978"
      binary "pvecsictl-darwin-arm64", target: "pvecsictl-darwin-arm64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-linux-amd64"
      sha256 "52883000cd49441a5d25007542dbbaf5def057c71cb1c40bc0ea5907e74f7d72"
      binary "pvecsictl-linux-amd64", target: "pvecsictl-linux-amd64"
    end
    on_arm do
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-linux-arm64"
      sha256 "c2360f68bbd64e9e1a9232b1c38b1e1b1c94e6cd41ea71d7fce6d12166174df5"
      binary "pvecsictl-linux-arm64", target: "pvecsictl-linux-arm64"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pvecsictl-darwin-#{arch}"]
    end
  end

  # No zap stanza required
end
