# This file was generated by GoReleaser. DO NOT EDIT.
cask "pvecsictl" do
  arch arm: "arm64", intel: "amd64"
  os macos: "darwin", linux: "linux"
  binary "pvecsictl-#{os}-#{arch}", target: "pvecsictl"

  version "0.19.1"

  on_macos do
    on_intel do
      sha256 "7ae71daa9c21a6f0d253a5c787abef5b3f0330ae55dda681b9b5d6becb78e5ac"
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-darwin-amd64"
      binary "pvecsictl-darwin-amd64", target: "pvecsictl-darwin-amd64"
    end
    on_arm do
      sha256 "3480acf281e5157c8b7cdd492a5af9096e7845d2f5da0475923de48abb5544ca"
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-darwin-arm64"
      binary "pvecsictl-darwin-arm64", target: "pvecsictl-darwin-arm64"
    end
  end

  on_linux do
    on_intel do
      sha256 "00048c77656e7481acfc5b190e374651ade71e905aeb3f214282b9da4bdcf709"
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-linux-amd64"
      binary "pvecsictl-linux-amd64", target: "pvecsictl-linux-amd64"
    end
    on_arm do
      sha256 "5ff14fe778a6ebc39a40cac1f864d1095515e302d5b41009075e8306b3646c72"
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v#{version}/pvecsictl-linux-arm64"
      binary "pvecsictl-linux-arm64", target: "pvecsictl-linux-arm64"
    end
  end

  name "pvecsictl"
  desc "Proxmox VE CSI Mutate tool"
  homepage "https://github.com/sergelogvinov/proxmox-csi-plugin"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pvecsictl-darwin-#{arch}"]
    end
  end

  # No zap stanza required

end
