# This file was generated by GoReleaser. DO NOT EDIT.
cask "talos-mcp" do
  arch arm: "arm64", intel: "amd64"

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "cb195379efdf948138c130ee5d4acb9df73b731a28d6907e60b66afe8c090d97"
      url "https://github.com/sergelogvinov/talos-mcp/releases/download/v#{version}/talos-mcp_darwin_arm64"
      binary "talos-mcp_darwin_arm64", target: "talos-mcp"
    end
    on_intel do
      sha256 "43e2bfe1ddc2a2414d33b138163d6c10b6d8456515428e4a205fa329526d84ff"
      url "https://github.com/sergelogvinov/talos-mcp/releases/download/v#{version}/talos-mcp_darwin_amd64"
      binary "talos-mcp_darwin_amd64", target: "talos-mcp"
    end
  end
  on_linux do
    on_arm do
      sha256 "e1a40fa785b87c4676ad40e16c547c8b9fef80737201bfcb48d2b29a4fe18320"
      url "https://github.com/sergelogvinov/talos-mcp/releases/download/v#{version}/talos-mcp_linux_arm64"
      binary "talos-mcp_linux_arm64", target: "talos-mcp"
    end
    on_intel do
      sha256 "f5cd5ade472caf011d6ceaae90ca3318168f430e82a332228bbaac9650c1fbc7"
      url "https://github.com/sergelogvinov/talos-mcp/releases/download/v#{version}/talos-mcp_linux_amd64"
      binary "talos-mcp_linux_amd64", target: "talos-mcp"
    end
  end

  name "talos-mcp"
  desc "Talos MCP is an opinionated MCP server for Talos Linux"
  homepage "https://github.com/sergelogvinov/talos-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/talos-mcp_darwin_#{arch}"]
    end
  end

  # No zap stanza required
end
