# This file was generated by GoReleaser. DO NOT EDIT.
cask "talos-mcp" do
  arch arm: "arm64", intel: "amd64"

  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f6649795241e9f3ba04454af2e1567ffe4407d0c259095a36d2d1f7070acf285"
      url "https://github.com/sergelogvinov/talos-mcp/releases/download/v#{version}/talos-mcp_darwin_arm64"
      binary "talos-mcp_darwin_arm64", target: "talos-mcp"
    end
    on_intel do
      sha256 "f4434392eb0a8bcfadbd5c63c1ca3516894e4277570501da661d1c22ad0b45e0"
      url "https://github.com/sergelogvinov/talos-mcp/releases/download/v#{version}/talos-mcp_darwin_amd64"
      binary "talos-mcp_darwin_amd64", target: "talos-mcp"
    end
  end
  on_linux do
    on_arm do
      sha256 "ed47f3c3b261d0ca2d002d77da021cb742622c47f18d146da18482bba58165aa"
      url "https://github.com/sergelogvinov/talos-mcp/releases/download/v#{version}/talos-mcp_linux_arm64"
      binary "talos-mcp_linux_arm64", target: "talos-mcp"
    end
    on_intel do
      sha256 "470ce89bbcc026bcf01e0c8448868637cf3c9e9b75e0d06ca81adc32edbc5d80"
      url "https://github.com/sergelogvinov/talos-mcp/releases/download/v#{version}/talos-mcp_linux_amd64"
      binary "talos-mcp_linux_amd64", target: "talos-mcp"
    end
  end

  name "talos-mcp"
  desc "Talos MCP is an opinionated MCP server for Talos Linux"
  homepage "https://github.com/sergelogvinov/talos-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/talos-mcp_darwin_#{arch}"]
    end
  end

  # No zap stanza required
end
