# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pvecsictl < Formula
  desc "Proxmox VE CSI Mutate tool"
  homepage "https://github.com/sergelogvinov/proxmox-csi-plugin"
  version "0.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v0.10.0/pvecsictl-darwin-amd64"
      sha256 "9dc3c49441baca81d15ae214d6231874bc1702cdb5057938b02b8ff450fc80bf"

      def install
        bin.install "pvecsictl-darwin-amd64" => "pvecsictl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v0.10.0/pvecsictl-darwin-arm64"
      sha256 "818782426914e9eb013956d079f5b78e5c6e07a09a62e82c25e72b6281230e9c"

      def install
        bin.install "pvecsictl-darwin-arm64" => "pvecsictl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v0.10.0/pvecsictl-linux-amd64"
        sha256 "b76a7956701279640c200a9a13f2ef7a1dc6236c7f39a5e02e12c2c9159947d1"

        def install
          bin.install "pvecsictl-linux-amd64" => "pvecsictl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sergelogvinov/proxmox-csi-plugin/releases/download/v0.10.0/pvecsictl-linux-arm64"
        sha256 "b0b9789726668456a7a7b0fefd184a542004e693b5ab1309e4d0f99733f4c6b3"

        def install
          bin.install "pvecsictl-linux-arm64" => "pvecsictl"
        end
      end
    end
  end

  test do
    system "#{bin}/pvecsictl -v"
  end
end
